name: Node.js CI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: npm install, build, and test
        run: |
          npm install
          npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/BarlogM-Unda.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
